// section1_cube_geojump.c
// Section 1: Cube × Geo Jump — 6-Direction to 15-Pair Mapping
//
// Mapping:
//   6 directions (A-F) → C(6,2) = 15 pairs
//   15 pairs → 15 geo_jump towers
//   48 addresses per tower = GEO_BLOCK (weight values per pair)
//   2 polarities (+/-) = complementary views
//   Total: 15 × 48 × 2 = 1440 = GEO_FIBO_CLOCK
//
// The 15 pairs:
//   ab, ac, ad, ae, af   (A with each other)
//   bc, bd, be, bf       (B with each other)
//   cd, ce, cf           (C with each other)
//   de, df               (D with each other)
//   ef                   (E with F)
//
// Compile: gcc -O2 -std=c11 -Icollection/dgls/geo/include -Icore \
//              -o section1_cube_geojump.exe \
//              runner/explore/section1_cube_geojump.c \
//              collection/dgls/geo/src/geo_jump.c -lm
// Run:     section1_cube_geojump.exe
//
// ============================================================

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <math.h>
#include <time.h>
#include <assert.h>

// ── Geo Jump ──
#include "geo_jump.h"   // from collection/dgls/geo/include/

// ── Constants ──
#define N_DIRS      6       // A B C D E F
#define N_PAIRS     15      // C(6,2)
#define ADDR_PER_TOWER  48  // GEO_BLOCK = 48
#define N_POLAR     2       // +, -
#define TOTAL_ADDR  (N_PAIRS * ADDR_PER_TOWER * N_POLAR)  // 1440

static const char DIR_NAMES[6] = {'A','B','C','D','E','F'};

// Pair mapping: (d1, d2) where d1 < d2, index 0..14
// Generated by C(6,2): for i in 0..4, j in i+1..5
static int pair_of_dirs(int d1, int d2)
{
    if (d1 < 0 || d1 >= N_DIRS || d2 < 0 || d2 >= N_DIRS) return -1;
    if (d1 == d2) return -1;
    if (d1 > d2) { int t = d1; d1 = d2; d2 = t; }
    // Count: for i=0..d1-1, (5-i) options, then offset within d1
    int idx = 0;
    for (int i = 0; i < d1; i++) idx += (N_DIRS - 1 - i);
    idx += (d2 - d1 - 1);
    return idx;
}

static const char *pair_name(int pi)
{
    if (pi < 0 || pi >= N_PAIRS) return "??";
    // Find d1,d2 from pair index
    int d1 = 0, d2 = 1;
    while (pi > 0) {
        int remaining = N_DIRS - 1 - d1;
        if (pi < remaining) { d2 = d1 + 1 + pi; break; }
        pi -= remaining;
        d1++;
    }
    if (d1 >= N_DIRS) return "??";
    if (d2 <= d1) d2 = d1 + 1;
    static char buf[4];
    buf[0] = DIR_NAMES[d1]; buf[1] = DIR_NAMES[d2]; buf[2] = '\0';
    return buf;
}

// ── Mapping: (pair_id, addr, polar) → geo_jump node_id ──
// pair_id: 0..14 (which C(6,2) pair)
// addr:    0..47 (weight value within pair)
// polar:   0=positive, 1=negative (capo shift)
//
// Node = pair_id * GEO_BLOCK + addr
// With polarity: polar=1 adds capo shift of GEO_TOWER/2

static uint32_t mapping_lookup(int pair_id, int addr, int polar)
{
    if (pair_id < 0 || pair_id >= N_PAIRS) return 0;
    if (addr  < 0 || addr  >= ADDR_PER_TOWER) addr = 0;
    if (polar < 0 || polar >= N_POLAR) polar = 0;

    // Base node in tower: pair_id * GEO_TOWER + addr
    // Each pair owns one tower (GEO_TOWER = 144 addresses)
    uint32_t node = (uint32_t)(pair_id * GEO_TOWER + addr);

    // Polarity: negative flips to complementary tower
    if (polar == 1)
        node = GEO_WRAP(node + GEO_TOWER / 2);

    return node;
}

// Reverse: node_id → (pair_id, addr, polar)
static void mapping_reverse(uint32_t node_id, int *pair_id, int *addr, int *polar)
{
    uint32_t n = node_id % GEO_FULL;
    int tower = (int)(n / GEO_TOWER);
    int offset = (int)(n % GEO_TOWER);

    // Each tower (144) splits: 0..71 = +polar, 72..143 = -polar
    *pair_id = tower;
    *polar = (offset >= (int)(GEO_TOWER / 2)) ? 1 : 0;
    *addr = *polar ? (offset - GEO_TOWER / 2) : offset;
    if (*addr >= ADDR_PER_TOWER) *addr %= ADDR_PER_TOWER;
}

// ── Weight store ──
// A simplified store: each (pair_id, addr, polar) holds one weight
#define WEIGHT_CELLS TOTAL_ADDR

typedef struct {
    int8_t data[WEIGHT_CELLS];
    int    written;
} WeightStore;

static void ws_init(WeightStore *ws)
{
    memset(ws->data, 0, sizeof(ws->data));
    ws->written = 0;
}

static int ws_idx(int pair_id, int addr, int polar)
{
    return pair_id * ADDR_PER_TOWER * N_POLAR + polar * ADDR_PER_TOWER + addr;
}

static void ws_write(WeightStore *ws, int pair_id, int addr, int polar, int8_t val)
{
    ws->data[ws_idx(pair_id, addr, polar)] = val;
    ws->written++;
}

static int8_t ws_read(const WeightStore *ws, int pair_id, int addr, int polar)
{
    return ws->data[ws_idx(pair_id, addr, polar)];
}

// ── Tests ──

static int t1_pair_enumeration(void)
{
    printf("=== T1: C(6,2) pair enumeration ===\n");
    int ok = 1, visited[N_PAIRS];
    memset(visited, 0, sizeof(visited));

    printf("  All 15 pairs:\n");
    for (int d1 = 0; d1 < N_DIRS; d1++) {
        for (int d2 = d1+1; d2 < N_DIRS; d2++) {
            int pi = pair_of_dirs(d1, d2);
            if (pi < 0 || pi >= N_PAIRS) {
                printf("  FAIL (%c,%c) → %d\n", DIR_NAMES[d1], DIR_NAMES[d2], pi);
                ok = 0;
            } else {
                visited[pi]++;
                printf("    %c%c → pair %2d  (%s)\n",
                       DIR_NAMES[d1], DIR_NAMES[d2], pi, pair_name(pi));
            }
        }
    }

    // Verify each pair visited exactly once
    for (int i = 0; i < N_PAIRS; i++) {
        if (visited[i] != 1) {
            printf("  FAIL: pair %d visited %d times\n", i, visited[i]);
            ok = 0;
        }
    }

    printf("  %s\n", ok ? "PASS" : "FAIL");
    return ok;
}

static int t2_address_space(void)
{
    printf("\n=== T2: Address space (%d addresses) ===\n", TOTAL_ADDR);

    printf("  15 pairs × 48 addr × 2 polar = %d\n", TOTAL_ADDR);
    printf("  GEO_FIBO_CLOCK = %u\n", GEO_FIBO_CLOCK);
    printf("  Match: %s\n", TOTAL_ADDR == GEO_FIBO_CLOCK ? "YES (=1440)" : "NO");

    // Test mapping uniqueness
    uint8_t visited[GEO_FULL];
    memset(visited, 0, sizeof(visited));
    int collisions = 0;

    for (int pi = 0; pi < N_PAIRS; pi++) {
        for (int a = 0; a < ADDR_PER_TOWER; a++) {
            for (int po = 0; po < N_POLAR; po++) {
                uint32_t node = mapping_lookup(pi, a, po);
                if (node >= GEO_FULL) {
                    printf("  FAIL: node %u out of range\n", node);
                    return 0;
                }
                if (visited[node]) collisions++;
                visited[node] = 1;
            }
        }
    }

    uint32_t unique = 0;
    for (uint32_t i = 0; i < GEO_FULL; i++) unique += visited[i];
    printf("  Unique nodes used: %u/%u (%d expected)\n",
           unique, GEO_FULL, TOTAL_ADDR);
    printf("  Collisions: %d\n", collisions);

    // Test roundtrip: node → reverse → node
    int rev_err = 0;
    for (int pi = 0; pi < N_PAIRS && rev_err < 3; pi++) {
        for (int a = 0; a < ADDR_PER_TOWER && rev_err < 3; a++) {
            for (int po = 0; po < N_POLAR && rev_err < 3; po++) {
                uint32_t node = mapping_lookup(pi, a, po);
                int rpi, ra, rpo;
                mapping_reverse(node, &rpi, &ra, &rpo);
                if (rpi != pi || ra != a || rpo != po) {
                    printf("  FAIL roundtrip: (%d,%d,%d)→node=%u→(%d,%d,%d)\n",
                           pi, a, po, node, rpi, ra, rpo);
                    rev_err++;
                }
            }
        }
    }

    int pass = (collisions == 0 && rev_err == 0);
    printf("  %s\n", pass ? "PASS" : "FAIL");
    return pass;
}

static int t3_write_read_roundtrip(void)
{
    printf("\n=== T3: Write→Read roundtrip (1440 cells) ===\n");

    WeightStore ws;
    ws_init(&ws);

    // Fill with deterministic values
    for (int pi = 0; pi < N_PAIRS; pi++) {
        for (int a = 0; a < ADDR_PER_TOWER; a++) {
            for (int po = 0; po < N_POLAR; po++) {
                int8_t val = (int8_t)((pi * 47 + a * 13 + po * 7) % 256 - 128);
                ws_write(&ws, pi, a, po, val);
            }
        }
    }

    // Read back
    int err = 0;
    for (int pi = 0; pi < N_PAIRS && err < 5; pi++) {
        for (int a = 0; a < ADDR_PER_TOWER && err < 5; a++) {
            for (int po = 0; po < N_POLAR && err < 5; po++) {
                int8_t expected = (int8_t)((pi * 47 + a * 13 + po * 7) % 256 - 128);
                int8_t got = ws_read(&ws, pi, a, po);
                if (got != expected) {
                    printf("  FAIL pair=%s addr=%d polar=%d: expect %d got %d\n",
                           pair_name(pi), a, po, expected, got);
                    err++;
                }
            }
        }
    }

    printf("  %s: %d err / %d writes\n", err ? "FAIL" : "PASS", err, ws.written);
    return err == 0;
}

static int t4_geo_jump_bridge(void)
{
    printf("\n=== T4: GeoJump bridge (node_id → jump types) ===\n");

    int ok = 1;

    // Take a sample of our mapped nodes and verify geo_jump operations work
    for (int pi = 0; pi < 3 && ok; pi++) {
        for (int a = 0; a < 4 && ok; a++) {
            uint32_t node = mapping_lookup(pi, a, 0);  // +polar

            // Apply each jump type
            uint32_t h = geo_jump(node, JUMP_HILBERT, 0);
            uint32_t p = geo_jump(node, JUMP_PEANO, 0);
            uint32_t m = geo_jump(node, JUMP_MOD, 0);
            uint32_t inv = geo_jump(node, JUMP_INVERT, 0);

            // Verify all stay in range
            if (h >= GEO_FULL || p >= GEO_FULL || m >= GEO_FULL || inv >= GEO_FULL) {
                printf("  FAIL jump out of range at node=%u\n", node);
                ok = 0;
            }

            // geo_pentagon_id should work on any node
            uint32_t pent = geo_pentagon_id(node);
            if (pent < 1 || pent > GEO_PENTAGONS) {
                printf("  FAIL pentagon_id=%u at node=%u\n", pent, node);
                ok = 0;
            }

            // geo_clock_tick should be in 0..1439
            uint32_t tick = geo_clock_tick(node);
            if (tick >= GEO_FIBO_CLOCK) {
                printf("  FAIL clock_tick=%u at node=%u\n", tick, node);
                ok = 0;
            }
        }
    }

    printf("  Jump types tested: Hilbert, Peano, Mod, Invert\n");
    printf("  %s\n", ok ? "PASS" : "FAIL");
    return ok;
}

static int t5_polar_complement(void)
{
    printf("\n=== T5: Polar complement ===\n");

    // +polar and -polar should map to complementary views
    // Test: write to +polar, check -polar is empty (different address)
    WeightStore ws;
    ws_init(&ws);

    // Write at +polar for all pairs
    for (int pi = 0; pi < N_PAIRS; pi++) {
        for (int a = 0; a < ADDR_PER_TOWER; a++) {
            ws_write(&ws, pi, a, 0, (int8_t)(pi + a));
        }
    }

    // Read at -polar — should be 0 (not written)
    int zero_count = 0;
    for (int pi = 0; pi < N_PAIRS; pi++) {
        for (int a = 0; a < ADDR_PER_TOWER; a++) {
            if (ws_read(&ws, pi, a, 1) == 0) zero_count++;
        }
    }

    // Percentage of -polar reads that returned 0 (not written)
    double pct = 100.0 * zero_count / (N_PAIRS * ADDR_PER_TOWER);
    printf("  -polar reads returning 0: %d/%d (%.1f%%) — expect 100%% if separate\n",
           zero_count, N_PAIRS * ADDR_PER_TOWER, pct);

    // Verify +polar values intact
    int err = 0;
    for (int pi = 0; pi < N_PAIRS && err < 3; pi++) {
        for (int a = 0; a < ADDR_PER_TOWER && err < 3; a++) {
            int8_t expected = (int8_t)(pi + a);
            int8_t got = ws_read(&ws, pi, a, 0);
            if (got != expected) {
                printf("  FAIL +polar pair=%s addr=%d: expect %d got %d\n",
                       pair_name(pi), a, expected, got);
                err++;
            }
        }
    }

    int pass = (pct > 90 && err == 0);  // >90% of -polar should be separate
    printf("  %s\n", pass ? "PASS" : "FAIL");
    return pass;
}

static int t6_benchmark(void)
{
    printf("\n=== T6: Speed benchmark (500K ops) ===\n");

    WeightStore ws;
    ws_init(&ws);

    uint32_t N = 500000;
    clock_t t0, t1;
    double sec;

    t0 = clock();
    for (uint32_t i = 0; i < N; i++) {
        int pi = i % N_PAIRS;
        int a  = (i / N_PAIRS) % ADDR_PER_TOWER;
        int po = (i / (N_PAIRS * ADDR_PER_TOWER)) % N_POLAR;
        int8_t val = (int8_t)((i * 37) % 256 - 128);
        ws_write(&ws, pi, a, po, val);
    }
    t1 = clock();
    sec = (double)(t1 - t0) / CLOCKS_PER_SEC;
    printf("  Write: %.0f ops/s (%.1f ns/op)\n", N / sec, 1e9 / (N / sec));

    int64_t sum = 0;
    t0 = clock();
    for (uint32_t i = 0; i < N; i++) {
        int pi = i % N_PAIRS;
        int a  = (i / N_PAIRS) % ADDR_PER_TOWER;
        int po = (i / (N_PAIRS * ADDR_PER_TOWER)) % N_POLAR;
        sum += ws_read(&ws, pi, a, po);
    }
    t1 = clock();
    sec = (double)(t1 - t0) / CLOCKS_PER_SEC;
    printf("  Read:  %.0f ops/s (%.1f ns/op)\n", N / sec, 1e9 / (N / sec));

    // Benchmark mapping + geo_jump
    t0 = clock();
    for (uint32_t i = 0; i < N; i++) {
        int pi = i % N_PAIRS;
        int a  = (i / N_PAIRS) % ADDR_PER_TOWER;
        int po = (i / (N_PAIRS * ADDR_PER_TOWER)) % N_POLAR;
        uint32_t node = mapping_lookup(pi, a, po);
        uint32_t jumped = geo_jump(node, JUMP_MOD, 0);
        sum += jumped;
    }
    t1 = clock();
    sec = (double)(t1 - t0) / CLOCKS_PER_SEC;
    printf("  map+jump: %.0f ops/s (%.1f ns/op)\n", N / sec, 1e9 / (N / sec));

    printf("  PASS\n");
    return 1;
}

// ── Main ──

int main(void)
{
    printf("============================================================\n");
    printf("  Section 1: Cube × Geo Jump\n");
    printf("  6 dirs → C(6,2)=15 pairs → 15 towers × 48 addr × 2 polar\n");
    printf("============================================================\n");
    printf("\n");
    printf("  Dirs:  %d (A B C D E F)\n", N_DIRS);
    printf("  Pairs: %d = C(6,2)\n", N_PAIRS);
    printf("  Addr:  %d per tower\n", ADDR_PER_TOWER);
    printf("  Polar: %d (+ / -)\n", N_POLAR);
    printf("  Total: %d = GEO_FIBO_CLOCK\n", TOTAL_ADDR);
    printf("  GEO_FULL = %u\n", GEO_FULL);
    printf("  GEO_TOWER = %u\n", GEO_TOWER);
    printf("  GEO_BLOCK = %u\n", GEO_BLOCK);
    printf("\n");

    int pass = 0, total = 0;

    total++; pass += t1_pair_enumeration();
    total++; pass += t2_address_space();
    total++; pass += t3_write_read_roundtrip();
    total++; pass += t4_geo_jump_bridge();
    total++; pass += t5_polar_complement();
    total++; pass += t6_benchmark();

    printf("\n============================================================\n");
    printf("  FINAL: %d/%d PASS\n", pass, total);
    printf("============================================================\n");

    return (pass == total) ? 0 : 1;
}
