/*
 * safetensors_analyze.c — Analyze safetensors BF16 weights
 *
 * Uses binary index file (generated by gen_st_index.py) + raw tensor data.
 * Applies geometric codecs for comparison.
 *
 * Build: gcc -O2 -o safetensors_analyze.exe safetensors_analyze.c -lm
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <math.h>

#define BLOCK_SIZE 32

/* BF16 -> float */
static inline float bf16_to_float(uint16_t bf16) {
    uint32_t sign = (uint32_t)(bf16 >> 15) << 31;
    uint32_t exp  = (bf16 >> 7) & 0xFF;
    uint32_t mant = bf16 & 0x7F;
    uint32_t f32;
    if (exp == 0) {
        if (mant == 0) f32 = sign;
        else f32 = sign | ((127 - 126) << 23) | (mant << 16);
    } else if (exp == 0xFF) {
        f32 = sign | 0x7F800000 | (mant << 16);
    } else {
        f32 = sign | (exp << 23) | (mant << 16);
    }
    float result;
    memcpy(&result, &f32, 4);
    return result;
}

static inline int8_t bf16_to_int8_approx(uint16_t bf16) {
    float f = bf16_to_float(bf16);
    if (f > 127.0f) return 127;
    if (f < -128.0f) return -128;
    return (int8_t)(f + (f >= 0 ? 0.5f : -0.5f));
}

static inline int bf16_is_zero(uint16_t bf16) { return (bf16 & 0x7FFF) == 0; }
static inline int bf16_exponent(uint16_t bf16) { return (bf16 >> 7) & 0xFF; }

/* ============================================================
 * Stats
 * ============================================================ */
typedef struct {
    uint64_t total;
    uint64_t zeros;
    uint64_t pos, neg;
    double   sum, sum_sq;
    float    min_val, max_val;
    uint64_t exp_bins[256];
    uint64_t hist[256]; /* int8 approx */
} Stats;

static void stats_init(Stats *s) { memset(s, 0, sizeof(*s)); s->min_val = 1e30f; s->max_val = -1e30f; }

static void stats_add(Stats *s, uint16_t bf16) {
    float f = bf16_to_float(bf16);
    int8_t a = bf16_to_int8_approx(bf16);
    s->total++;
    if (bf16_is_zero(bf16)) s->zeros++;
    if (f > 0) s->pos++; else if (f < 0) s->neg++;
    s->sum += f; s->sum_sq += (double)f * f;
    if (f < s->min_val) s->min_val = f;
    if (f > s->max_val) s->max_val = f;
    s->exp_bins[bf16_exponent(bf16)]++;
    int h = (int)a + 128; if (h < 0) h = 0; if (h > 255) h = 255;
    s->hist[h]++;
}

static void stats_print(const Stats *s) {
    double mean = s->sum / s->total;
    double var = s->sum_sq / s->total - mean * mean;
    printf("\n  Total: %lu  Zeros: %lu (%.1f%%)  Pos: %lu (%.1f%%)  Neg: %lu (%.1f%%)\n",
        (unsigned long)s->total, (unsigned long)s->zeros, 100.0*s->zeros/s->total,
        (unsigned long)s->pos, 100.0*s->pos/s->total, (unsigned long)s->neg, 100.0*s->neg/s->total);
    printf("  Mean: %.6f  StdDev: %.6f  Min: %.4f  Max: %.4f\n",
        mean, sqrt(var > 0 ? var : 0), s->min_val, s->max_val);

    /* Top exponents */
    printf("  Top exponents: ");
    for (int i = 0; i < 256; i++) {
        if (s->exp_bins[i] > s->total / 100) {
            printf("exp=%d(%lu,%.0f%%) ", i, (unsigned long)s->exp_bins[i], 100.0*s->exp_bins[i]/s->total);
        }
    }
    printf("\n");

    /* Top int8 values */
    printf("  Top int8 approx: ");
    int top[8] = {0}; uint64_t topc[8] = {0};
    for (int v = 0; v < 256; v++) {
        if (s->hist[v] == 0) continue;
        for (int i = 0; i < 8; i++) {
            if (s->hist[v] > topc[i]) {
                for (int j = 7; j > i; j--) { top[j] = top[j-1]; topc[j] = topc[j-1]; }
                top[i] = v; topc[i] = s->hist[v];
                break;
            }
        }
    }
    for (int i = 0; i < 8; i++) {
        if (topc[i] == 0) break;
        printf("val=%d(%lu,%.0f%%) ", top[i]-128, (unsigned long)topc[i], 100.0*topc[i]/s->total);
    }
    printf("\n");
}

/* ============================================================
 * Codec: Dominant value + exceptions per block
 * ============================================================ */
static uint64_t codec_dominant_exceptions(const uint16_t *data, int n) {
    uint64_t total = 0;
    int nblocks = (n + BLOCK_SIZE - 1) / BLOCK_SIZE;
    for (int b = 0; b < nblocks; b++) {
        int s = b * BLOCK_SIZE, e = s + BLOCK_SIZE;
        if (e > n) e = n;
        int bn = e - s;

        /* Find dominant value */
        uint64_t hist[65536] = {0};
        /* uint16_t dom = data[s]; */
        uint64_t domc = 0;
        for (int i = s; i < e; i++) {
            hist[data[i]]++;
            if (hist[data[i]] > domc) { domc = hist[data[i]]; /* dom = data[i]; */ }
        }
        int exc = bn - (int)domc;

        /* [dominant:2B][bitmap:4B][exception_values:2B each] */
        total += 2 + (BLOCK_SIZE + 7) / 8 + exc * 2;
    }
    return total;
}

/* ============================================================
 * Codec: Raw BF16 (baseline = raw_size)
 * ============================================================ */

/* ============================================================
 * Codec: int8 quantize (round BF16 to int8, store as 1 byte)
 * ============================================================ */

/* ============================================================
 * Codec: Exp-separate (shared dominant exponent per block + 7-bit mantissa)
 * ============================================================ */
static uint64_t codec_exp_separate(const uint16_t *data, int n) {
    uint64_t total = 0;
    int nblocks = (n + BLOCK_SIZE - 1) / BLOCK_SIZE;
    for (int b = 0; b < nblocks; b++) {
        int s = b * BLOCK_SIZE, e = s + BLOCK_SIZE;
        if (e > n) e = n;
        int bn = e - s;

        /* Find dominant exponent */
        int ehist[256] = {0};
        /* int dom_exp = 0, */ int dom_cnt = 0;
        for (int i = s; i < e; i++) {
            int exp = bf16_exponent(data[i]);
            ehist[exp]++;
            if (ehist[exp] > dom_cnt) { dom_cnt = ehist[exp]; /* dom_exp = exp; */ }
        }
        int non_dom = bn - dom_cnt;

        /* [dom_exp:1B][non_dom_count:1B][mantissa_per_weight:1B each for non-dominant]
         * For dominant exp weights: just store mantissa (7 bits, pack into bytes)
         * For non-dominant: store full BF16 (2 bytes each)
         * Plus bitmap: 1 bit per weight (0=dominant exp, 1=non-dominant)
         */
        total += 1 + 1 + (BLOCK_SIZE + 7) / 8; /* header + bitmap */
        total += (dom_cnt * 7 + 7) / 8; /* mantissas for dominant exp */
        total += non_dom * 2; /* full BF16 for non-dominant */
    }
    return total;
}

/* ============================================================
 * Main
 * ============================================================ */
int main(int argc, char **argv) {
    const char *st_path = (argc > 1) ? argv[1] : "I:/model/smolVLM-256M-Instruct/model.safetensors";
    const char *idx_path = (argc > 2) ? argv[2] : "I:/FGLS_new/beam_addressing/smolvlm.idx";

    printf("╔══════════════════════════════════════════════════╗\n");
    printf("║  Safetensors BF16 Codec Analysis                ║\n");
    printf("╚══════════════════════════════════════════════════╝\n\n");
    printf("Model: %s\n", st_path);

    /* Read index */
    FILE *fidx = fopen(idx_path, "rb");
    if (!fidx) { fprintf(stderr, "Cannot open %s\n", idx_path); return 1; }

    uint32_t ntensors;
    fread(&ntensors, 4, 1, fidx);
    printf("Tensors: %u (from index)\n\n", ntensors);

    /* Open safetensors data */
    FILE *fst = fopen(st_path, "rb");
    if (!fst) { fprintf(stderr, "Cannot open %s\n", st_path); fclose(fidx); return 1; }

    /* Skip header */
    uint64_t hdr_len;
    fread(&hdr_len, 8, 1, fst);
    fseek(fst, (long)hdr_len, SEEK_CUR);
    uint64_t data_offset = 8 + hdr_len;

    Stats global;
    stats_init(&global);

    uint64_t total_raw = 0, total_int8 = 0, total_dominant = 0, total_exp_sep = 0;
    int processed = 0;

    for (uint32_t i = 0; i < ntensors; i++) {
        /* Read index entry */
        uint16_t name_len;
        fread(&name_len, 2, 1, fidx);
        char name[256];
        fread(name, 1, name_len, fidx);
        name[name_len] = '\0';

        uint8_t dtype_len;
        fread(&dtype_len, 1, 1, fidx);
        char dtype[16];
        fread(dtype, 1, dtype_len, fidx);
        dtype[dtype_len] = '\0';

        uint8_t ndim;
        fread(&ndim, 1, 1, fidx);
        int64_t shape[8];
        for (int d = 0; d < ndim; d++) fread(&shape[d], 8, 1, fidx);

        uint64_t off_start, off_end;
        fread(&off_start, 8, 1, fidx);
        fread(&off_end, 8, 1, fidx);

        uint64_t raw_size = off_end - off_start;
        uint64_t ne = 1;
        for (int d = 0; d < ndim; d++) ne *= (uint64_t)shape[d];

        /* Only process BF16 tensors with >1000 elements */
        if (ne < 1000 || (strcmp(dtype, "BF16") != 0 && strcmp(dtype, "F16") != 0)) continue;

        /* Read data */
        uint16_t *data = (uint16_t*)malloc(raw_size);
        if (!data) continue;
        fseek(fst, (long)(data_offset + off_start), SEEK_SET);
        if (fread(data, 1, raw_size, fst) != raw_size) { free(data); continue; }

        int n = (int)ne;

        /* Stats */
        Stats ts; stats_init(&ts);
        for (int j = 0; j < n; j++) stats_add(&ts, data[j]);

        /* Accumulate global */
        global.total += ts.total;
        global.zeros += ts.zeros;
        global.pos += ts.pos;
        global.neg += ts.neg;
        global.sum += ts.sum;
        global.sum_sq += ts.sum_sq;
        if (ts.min_val < global.min_val) global.min_val = ts.min_val;
        if (ts.max_val > global.max_val) global.max_val = ts.max_val;
        for (int e = 0; e < 256; e++) global.exp_bins[e] += ts.exp_bins[e];
        for (int h = 0; h < 256; h++) global.hist[h] += ts.hist[h];

        /* Codecs */
        uint64_t c_raw = raw_size; /* BF16 raw */
        uint64_t c_int8 = (uint64_t)n; /* int8 quantize */
        uint64_t c_dom = codec_dominant_exceptions(data, n);
        uint64_t c_exp = codec_exp_separate(data, n);

        total_raw += c_raw;
        total_int8 += c_int8;
        total_dominant += c_dom;
        total_exp_sep += c_exp;

        printf("  [%2d] %-50s %5.1fMB  zeros=%.1f%% raw=%.2fx dom=%.2fx exp=%.2fx int8=%.2fx\n",
            i, name, (double)raw_size/1048576.0, 100.0*ts.zeros/ts.total,
            (double)c_raw/c_raw, (double)c_dom/c_raw, (double)c_exp/c_raw, (double)c_int8/c_raw);

        free(data);
        processed++;
    }

    printf("\n╔══════════════════════════════════════════════════╗\n");
    printf("║  Global Summary                                 ║\n");
    printf("╚══════════════════════════════════════════════════╝\n");
    stats_print(&global);

    printf("\n  Codec totals (BF16 tensors: %d):\n", processed);
    printf("  ─────────────────────────────────────\n");
    printf("  Raw BF16:           %7.1f MB  (1.000x)\n", (double)total_raw/1048576.0);
    printf("  Dominant+except:    %7.1f MB  (%.3fx)\n", (double)total_dominant/1048576.0, (double)total_dominant/total_raw);
    printf("  Exp-separate:       %7.1f MB  (%.3fx)\n", (double)total_exp_sep/1048576.0, (double)total_exp_sep/total_raw);
    printf("  Int8 quantize:      %7.1f MB  (%.3fx)\n", (double)total_int8/1048576.0, (double)total_int8/total_raw);

    fclose(fst);
    fclose(fidx);
    return 0;
}
