/*
 * bake_lut3.c — (compound,tet,vert,rot) tuple encoding
 * walk entry = 4-field tuple, guaranteed unique by construction
 * 12 × 5 × 4 × 3 = 720 ✓
 *
 * encode: [comp:4][tet:3][vert:2][rot:2] = 11 bits → uint32
 * cpair:  flip comp → chiral partner (11-comp)
 * BFS order over compounds (LetterCube style): chiral partner first
 */
#include <stdio.h>
#include <stdint.h>
#include <string.h>

#define N_COMP 12
#define N_TET   5
#define N_VERT  4
#define N_ROT   3

static uint32_t enc(int c,int t,int v,int r){
    return ((uint32_t)c<<7)|((uint32_t)t<<4)|((uint32_t)v<<2)|(uint32_t)r;
}
static uint32_t cpair(uint32_t e){
    int c=(e>>7)&0xF;
    return (e & 0x7Fu)|((uint32_t)(11-c)<<7);
}

static uint32_t WALK[720],PAIR[720];

static void build(void){
    /* BFS over 12 compounds: seed=0, neighbors=chiral+(c+1)%12 */
    int order[12], vis[12]={0}, qh=0,qt=0, q[12];
    q[qt++]=0; vis[0]=1;
    while(qh<qt){
        int c=q[qh++]; order[qh-1]=c;
        int nb[2]={11-c,(c+1)%12};
        for(int n=0;n<2;n++) if(!vis[nb[n]]){vis[nb[n]]=1;q[qt++]=nb[n];}
    }
    int idx=0;
    for(int oi=0;oi<12;oi++){
        int c=order[oi];
        for(int t=0;t<N_TET;t++)
            for(int r=0;r<N_ROT;r++)
                for(int v=0;v<N_VERT;v++){
                    WALK[idx]=enc(c,t,v,r);
                    PAIR[idx]=cpair(WALK[idx]);
                    idx++;
                }
    }
}

static int verify(void){
    for(int i=0;i<720;i++)
        for(int j=i+1;j<720;j++)
            if(WALK[i]==WALK[j]){fprintf(stderr,"dup %d=%d\n",i,j);return -1;}
    for(int i=0;i<720;i++)
        if(cpair(PAIR[i])!=WALK[i]){fprintf(stderr,"invol fail %d\n",i);return -2;}
    for(int i=0;i<720;i++){
        int f=0;
        for(int j=0;j<720;j++) if(PAIR[j]==WALK[i]){f=1;break;}
        if(!f){fprintf(stderr,"not surjective %d\n",i);return -3;}
    }
    /* check_cycle_720: WALK must form a single 720-element cycle
     * build next[] from walk order, then walk it and verify single cycle */
    {
        uint32_t next_enc[720];
        for(int i=0;i<720;i++)
            next_enc[i]=WALK[(i+1)%720];
        /* build enc->idx map to follow cycle */
        uint16_t ridx[2048]; memset(ridx,0xFF,sizeof(ridx));
        for(int i=0;i<720;i++) ridx[WALK[i]&0x7FF]=(uint16_t)i;
        /* walk the cycle */
        uint8_t seen[720]={0};
        uint16_t x=0;
        for(int i=0;i<720;i++){
            if(seen[x]){fprintf(stderr,"cycle_720: revisit at step %d (idx=%u)\n",i,x);return -4;}
            seen[x]=1;
            uint32_t ne=next_enc[x];
            uint16_t nx=ridx[ne&0x7FF];
            if(nx==0xFFFF){fprintf(stderr,"cycle_720: broken at idx %u\n",x);return -4;}
            x=nx;
        }
        if(x!=0){fprintf(stderr,"cycle_720: did not close (landed at %u)\n",x);return -4;}
    }
    return 0;
}

int main(void){
    build();
    int vr=verify();
    fprintf(stderr,"verify: %s (code=%d)\n",vr==0?"PASS":"FAIL",vr);
    if(vr) return 1;

    printf("/* geo_temporal_lut.h — AUTO GENERATED by bake_lut3.c\n");
    printf(" * encode: [comp:4][tet:3][vert:2][rot:2]\n");
    printf(" * cpair:  comp → 11-comp (chiral mirror)\n */\n");
    printf("#ifndef GEO_TEMPORAL_LUT_H\n#define GEO_TEMPORAL_LUT_H\n");
    printf("#include <stdint.h>\n\n");
    printf("#define TEMPORAL_WALK_LEN  720u\n");
    printf("#define TRING_N_COMP        12u\n");
    printf("#define TRING_N_TET          5u\n");
    printf("#define TRING_N_VERT         4u\n");
    printf("#define TRING_N_ROT          3u\n\n");
    printf("/* decode helpers */\n");
    printf("#define TRING_COMP(e)  (((e)>>7)&0xFu)\n");
    printf("#define TRING_TET(e)   (((e)>>4)&0x7u)\n");
    printf("#define TRING_VERT(e)  (((e)>>2)&0x3u)\n");
    printf("#define TRING_ROT(e)   (((e)   )&0x3u)\n");
    printf("#define TRING_CPAIR(e) (((e)&0x7Fu)|((uint32_t)(11u-TRING_COMP(e))<<7))\n\n");
    printf("static const uint32_t GEO_WALK[720] = {\n");
    for(int i=0;i<720;i++){
        if(i%8==0)printf("    ");
        printf("0x%04Xu%s",WALK[i],i<719?",":"");
        if(i%8==7||i==719)printf("\n");
    }
    printf("};\n\nstatic const uint32_t GEO_PAIR[720] = {\n");
    for(int i=0;i<720;i++){
        if(i%8==0)printf("    ");
        printf("0x%04Xu%s",PAIR[i],i<719?",":"");
        if(i%8==7||i==719)printf("\n");
    }
    printf("};\n\n");

    /* reverse lookup: encoded value → walk index */
    printf("/* GEO_WALK_IDX: enc → position in walk (O(1) chunk address lookup) */\n");
    printf("static const uint16_t GEO_WALK_IDX[2048] = {\n");
    uint16_t ridx[2048]; memset(ridx,0xFF,sizeof(ridx));
    for(int i=0;i<720;i++) ridx[WALK[i]&0x7FF]=(uint16_t)i;
    for(int i=0;i<2048;i++){
        if(i%16==0)printf("    ");
        printf("%4u%s",ridx[i],i<2047?",":"");
        if(i%16==15||i==2047)printf("\n");
    }
    printf("};\n\n#endif /* GEO_TEMPORAL_LUT_H */\n");
    return 0;
}
